### ISSUE TITLE
[Android] no non-static method with name="init"

### ISSUE THREAD

**Issue by gitcalculus** [TalkingData/AdTracking_SDK_Unity#1]
The method "init" from this repo signature is needed like:
 (Context, String, String, String)
but the jar i got from talkingdata.com, named SaaS_AdTracking_Android_SDK_V4.0.33,  signature is 
(Context, String, String)
Is this a error? or i got the error jar?

**Comment by li-weiqiang** [comment]
开发中的代码被推到master分支，现已回退。
